name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with :
          repository: PXL-2TIN-DevOps-Resources/calculator-app-finished

      - name: Setup Node.js environment
      - uses: actions/setup-node@v4
        with:
          version: "18"
  
      - name: Install dependancies
        run: |
          sudo apt install -y npm
          sudo npm install
          
      - name: Test
        run: |
          sudo npm test --coverage

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: coverage/
          
