name: Files
on:
  workflow_dispatch:

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir test_dir
          cd test_dir
          touch file
          echo "korte tekst" > file
          cat file
